# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdf95a87554ba619d194919377baf9460e234bc0c6c1b545cb481b74778fd416fa71471f1aef2e1b902f0dfbe91f4fb0291661c85f2e811c628f446541d9ec1f

test:
  secret_key_base: b5049d933c5bdd6f660d59c4d7ea8fb7454f0844348d851b572067344bda91a07bee078f490c2297e475eeed568ebb9e05f24c9d19c413508b6239c5dc25a06c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
